### ISSUE TITLE
Any rollback results in "An error occured: Entity ID must be specified for Update"

### ISSUE THREAD

**Issue by BenGrav** [thomasdayman/XrmToolBox_AuditHistoryRollBack#1]
trying to rollback even just one item on any field on any entity we've tested throws this error

**Comment by thomasdayman** [comment]
I can confirm that I am getting the same issue. I will look into this for you as soon as I can

**Comment by thomasdayman** [comment]
@BenGrav I have fixed the bug and now waiting for the update to appear in XRMToolBox. Once you have the update please tell me if the bug is fixed and I will close this issue.

**Comment by BenGrav** [comment]
Just updated, and it's working beautifully, thanks a million! You have no idea how many hours of work this tools saves me!
